---
frontendPublicHttpProtocol: PUBLIC_PROTOCOL
environment: REFORM_ENVIRONMENT
nodeEnvironment: NODE_ENV
gitRevision: GIT_REVISION
externalHostNameUrl: EXTERNAL_HOSTNAME_URL
featureToggles:
  launchDarklyKey: LAUNCHDARKLY_KEY
app:
  useHttps: USE_HTTPS
  port: PORT
auth:
  jwt:
    secret: JWT_SECRET
services:
  pcqBackend:
    enabled: PCQ_BACKEND_ENABLED
    url: PCQ_BACKEND_URL
redis:
  host: REDIS_HOST
  port: REDIS_PORT
  password: REDIS_PASSWORD
  useTLS: REDIS_USE_TLS
  enabled: USE_REDIS
  secret: REDIS_SECRET
hostname: FRONTEND_HOSTNAME
enableTracking: ENABLE_TRACKING
links:
  survey: SURVEY
utils:
  api:
    retries: RETRIES_NUMBER
    retryDelay: RETRY_DELAY
appInsights:
  instrumentationKey: APPINSIGHTS_INSTRUMENTATION_KEY
